### ISSUE TITLE
Can't compile Multiwfn on M2 chip MacBook Air

### ISSUE THREAD

**Issue by KaguraSayuki** [digital-chemistry-laboratory/multiwfn-mac-build#10]
Hello, I tried to compile Multiwfn on a MacBook Air with an M2 chip, but it failed. The device environment and error message are as follows:

Device environment:
Device: MacBook Air (M2)
System version: macOS Sonoma 14.5
GCC version: 14.1.0

Multiwfn update date: May 25, 2024

Error message:
```
 3069 |         read(c200tmp,*) ((tmpelestr(i),tmpeffchg(i)),i=1,nread)
      |                        1
Error: Expecting variable in READ statement at (1)
```

**Comment by kjelljorner** [comment]
This is an error in the Multiwfn source, I've reported it so let's see if it can be fixed.

**Comment by KaguraSayuki** [comment]
Ok, thanks for your reply, I will try to compile the previous version first.😊

**Comment by kjelljorner** [comment]
Yes, so can check the previous commits on the `source_dist` branch before when the offending lines were introduced.

**Comment by KaguraSayuki** [comment]
The author has updated the source code of Multiwfn, and I was able to compile it successfully, so I will close this issue.
Thank you for helping me analyze the reason!
