### ISSUE TITLE
Multiwfn error in MacOS

### ISSUE THREAD

**Issue by sorahiro** [digital-chemistry-laboratory/multiwfn-mac-build#11]
Here is an error while installing Multiwfn, using macOS Sonoma  (M3 chip).
GCC, gfortran, etc. are installed from anaconda3.

-- The Fortran compiler identification is GNU 11.3.0
arm64-apple-darwin20.0.0-gfortran: warning: could not understand version ‘14.00.00’
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran
-- Check for working Fortran compiler: /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran - broken
CMake Error at /opt/anaconda3/share/cmake-3.26/Modules/CMakeTestFortranCompiler.cmake:59 (message):
  The Fortran compiler

    "/opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/m/multiwfn-mac-build/build/CMakeFiles/CMakeScratch/TryCompile-4ICsm5
    
    Run Build Command(s):/opt/anaconda3/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_80490/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_80490.dir/build.make CMakeFiles/cmTC_80490.dir/build
    Building Fortran object CMakeFiles/cmTC_80490.dir/testFortranCompiler.f.o
    /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.3 -c /Users/m/multiwfn-mac-build/build/CMakeFiles/CMakeScratch/TryCompile-4ICsm5/testFortranCompiler.f -o CMakeFiles/cmTC_80490.dir/testFortranCompiler.f.o
    arm64-apple-darwin20.0.0-gfortran: warning: ‘14.3’ is not valid for ‘-mmacosx-version-min’
    Linking Fortran executable cmTC_80490
    /opt/anaconda3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_80490.dir/link.txt --verbose=1
    /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.3 CMakeFiles/cmTC_80490.dir/testFortranCompiler.f.o -o cmTC_80490 
    arm64-apple-darwin20.0.0-gfortran: warning: ‘14.3’ is not valid for ‘-mmacosx-version-min’
    ld: -rpath can only be used when targeting Mac OS X 10.5 or later
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTC_80490] Error 1
    make: *** [cmTC_80490/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by kjelljorner** [comment]
Hello @sorahiro! This looks like a problem with detecting the compiler in CMake. We cannot assist with such errors as they are not specific to Multiwfn. You can try this compiler with another CMake build to see if it also fails there. I would recommend that you use gfortran installed from homebrew, and it might be that you need to use a specific version.
