### ISSUE TITLE
Any advice about GUI version?

### ISSUE THREAD

**Issue by lxsjgzs** [digital-chemistry-laboratory/multiwfn-mac-build#3]
Hello Sir,

Thank you for giving us a way to build Multiwfn form source code. I wonder if there has any way to build a GUI version form the source code. There has another issue about [building the PLATON](http://www.platonsoft.nl/xraysoft/Mac-OSX/platon/Platon_installation_on_a_Mac.pdf) with GUI form a linux source code,  I edited the Cmakelists.txt and try to add X11 library then to build it. Unfortunately, it can not work as expected. The GUI window can not appear.

The following is what I did.
###########################################

$ vim Cmakelists.txt

#Try to add X11 library
find_package(X11)
message(STATUS "X11_FOUND = ${X11_FOUND}")
message(STATUS "X11_INCLUDE_DIR = ${X11_INCLUDE_DIR}")
message(STATUS "X11_LIBRARIES = ${X11_LIBRARIES}")

##Comment the NoGUI folder: 
##${PROJECT_SOURCE_DIR}/noGUI/*.f90

#################################################

Thank you again for providing us a way to use Multiwfn on Mac and hope the GUI version can be proved to Mac.

Best wishes.

**Comment by kjelljorner** [comment]
Hello, thanks for your question. I looked into it, and it seems that it's not really possible at the moment, at least for Mac M1, as the Multiwfn GUI relies on DISLIN which is not available for this architecture yet. You can modify the source to also link to the X11 libraries:

```cmake
target_link_libraries(multiwfn PRIVATE ${BLAS_LIBRARIES} ${LAPACK_LIBRARIES} ${X11_LIBRARIES})
```

Then you would also need to link to your installation of DISLIN, but I cannot help you with that at the moment. Possibly DISLIN will support M1 in the future.

**Comment by lxsjgzs** [comment]
Thank you, I have read the `Cmakelists.txt` times and times try to add the `DISLIN` in, but I cannot do it well, sorry about that. Then I thought the Multiwfn official site has the Ver.3.7 source code of MACOS, then I downloaded it and try to find another method.

- The previous dependency such as `gcc gfortran ifort etc...` was installed fully in my computer by `Homebrew`

First, I downloaded the intel fortran and completed it to `PATH`, then I try to analyze the `makefile` between Multiwfn `3.7_src_for_mac` and `3.8_src_for_linux` then found some difference between the two files.

Next I move these files from `3.7_src_mac` to `3.8_src_linux`

- /my/OpenMotif/lib/PATH/libXm.dylib                 ### This line was edited in `Makefile`

These Lines were the files I moved to 3.8 linux source code folder.

- libdislin_d.11.1.0.dylib
- lapack.a
- blas.a

After that, I started to build from the source code by `make`, finally I got the Multiwfn executable file and add it to my PATH. It seems work well on my Intel MAC.

Finally, here is an `ld -lSystem`error` and the `ifort` seems cannot complete, I searched the same issue and add 
- \-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib and \-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system 

before the `-o Multiwfn` of final line print on terminal, then paste and execute the command manually, the file Multiwfn was built into current folder.

It is a way to use Multiwfn 3.8 dev on Intel CPU MacBook, but I still think the fastest and the most convenient way is using `cmake` and configure the DISLIN into `Cmakelists.txt`, but due to my current ability, I can not do it well.

_P.S._ Here is the final full Makefile file.



```
SIMD =
OPT = -O2 $(SIMD) -heap-arrays -diag-disable 8290,8291,6371,10316 -threads -qopenmp -qopenmp-link=static -fpp
LIB = /usr/local/lib/libXm.dylib ./libdislin_d.11.1.0.dylib ./lapack.a ./blas.a /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
FC = ifort
EXE = Multiwfn
LIBRETAPATH = ./libreta_hybrid

objects = define.o util.o plot.o Bspline.o sym.o libreta.o function.o GUI.o sub.o integral.o Lebedev-Laikov.o \
DFTxclib.o edflib.o fparser.o fileIO.o spectrum.o DOS.o Multiwfn.o 0123dim.o LSB.o \
population.o orbcomp.o bondorder.o topology.o excittrans.o otherfunc.o \
otherfunc2.o otherfunc3.o O1.o surfana.o procgriddata.o AdNDP.o fuzzy.o CDA.o basin.o \
orbloc.o visweak.o EDA.o CDFT.o ETS_NOCV.o atmraddens.o NAONBO.o grid.o PBC.o hyper_polar.o deloc_aromat.o \
minpack.o blockhrr_012345.o ean.o hrr_012345.o eanvrr_012345.o boysfunc.o naiveeri.o ryspoly.o

default : $(objects) 
	$(FC) $(OPT) $(objects) $(LIB) -o $(EXE)
	@echo " ------------------------------------------------------ " 
	@echo "          Multiwfn has been successfully built." 
	@echo " ------------------------------------------------------ " 

clean:
	rm -f $(EXE) *.o *.mod

#Only clean Multiwfn files, compiled libreta files are not affected
cleanmultiwfn:
	mkdir tmplib
	mv libreta.o ean.o hrr_012345.o blockhrr_012345.o eanvrr_012345.o boysfunc.o \
	libreta.mod hrr.mod blockhrr.mod ean.mod eanvrr.mod boysfunc.mod tmplib
	rm -f $(EXE) *.o *.mod
	mv tmplib/* ./
	rm -r tmplib

#Only clean libreta files, Multiwfn libreta files are not affected
cleanlibreta:
	rm -f $(EXE) libreta.o ean.o hrr_012345.o blockhrr_012345.o eanvrr_012345.o \
	boysfunc.o libreta.mod hrr.mod blockhrr.mod ean.mod eanvrr.mod boysfunc.mod


#Define modules that used by other files

dislin_d.mod : dislin_d.f90
	$(FC) $(OPT) -c dislin_d.f90

define.o : define.f90 dislin_d.mod
	$(FC) $(OPT) -c define.f90

Bspline.o : Bspline.f90
	$(FC) $(OPT) -c Bspline.f90

util.o : util.f90 define.o
	$(FC) $(OPT) -c util.f90

function.o : function.f90 define.o util.o Bspline.o libreta.o
	$(FC) $(OPT) -c function.f90

plot.o : plot.f90 define.o util.o
	$(FC) $(OPT) -c plot.f90

GUI.o : GUI.f90 define.o plot.o function.o
	$(FC) $(OPT) -c GUI.f90

modules = define.o util.o function.o plot.o GUI.o libreta.o


#Library or adpated third-part codes

DFTxclib.o : DFTxclib.F
	$(FC) $(OPT) -c DFTxclib.F

Lebedev-Laikov.o : Lebedev-Laikov.F
	$(FC) $(OPT) -c Lebedev-Laikov.F

sym.o : sym.F
	$(FC) $(OPT) -c sym.F

edflib.o : edflib.f90
	$(FC) $(OPT) -c edflib.f90

atmraddens.o : atmraddens.f90
	$(FC) $(OPT) -c atmraddens.f90

minpack.o : minpack.f90
	$(FC) $(OPT) -c minpack.f90
	
fparser.o : fparser.f90
	$(FC) $(OPT) -c fparser.f90
	

#Others

sub.o : sub.f90 $(modules)
	$(FC) $(OPT) -c sub.f90

integral.o : integral.f90 $(modules)
	$(FC) $(OPT) -c integral.f90

fileIO.o : fileIO.f90 $(modules)
	$(FC) $(OPT) -c fileIO.f90

spectrum.o : spectrum.f90 $(modules)
	$(FC) $(OPT) -c spectrum.f90

DOS.o : DOS.f90 $(modules)
	$(FC) $(OPT) -c DOS.f90

Multiwfn.o : Multiwfn.f90 $(modules)
	$(FC) $(OPT) -c Multiwfn.f90

0123dim.o : 0123dim.f90 $(modules)
	$(FC) $(OPT) -c 0123dim.f90

LSB.o : LSB.f90 $(modules)
	$(FC) $(OPT) -c LSB.f90

population.o : population.f90 $(modules)
	$(FC) $(OPT) -c population.f90

orbcomp.o : orbcomp.f90 $(modules)
	$(FC) $(OPT) -c orbcomp.f90

bondorder.o : bondorder.f90 $(modules)
	$(FC) $(OPT) -c bondorder.f90

topology.o : topology.f90 $(modules)
	$(FC) $(OPT) -c topology.f90

excittrans.o : excittrans.f90 $(modules)
	$(FC) $(OPT) -c excittrans.f90

otherfunc.o : otherfunc.f90 $(modules)
	$(FC) $(OPT) -c otherfunc.f90

otherfunc2.o : otherfunc2.f90 $(modules)
	$(FC) $(OPT) -c otherfunc2.f90

otherfunc3.o : otherfunc3.f90 $(modules)
	$(FC) $(OPT) -c otherfunc3.f90
	
O1.o : O1.f90 $(modules)
	$(FC) $(OPT1) -c O1.f90

surfana.o : surfana.f90 $(modules)
	$(FC) $(OPT) -c surfana.f90

procgriddata.o : procgriddata.f90 $(modules)
	$(FC) $(OPT) -c procgriddata.f90

AdNDP.o : AdNDP.f90 $(modules)
	$(FC) $(OPT) -c AdNDP.f90

fuzzy.o : fuzzy.f90 $(modules)
	$(FC) $(OPT) -c fuzzy.f90

CDA.o : CDA.f90 $(modules)
	$(FC) $(OPT) -c CDA.f90

basin.o : basin.f90 $(modules)
	$(FC) $(OPT) -c basin.f90

orbloc.o : orbloc.f90 $(modules)
	$(FC) $(OPT) -c orbloc.f90

visweak.o : visweak.f90 $(modules)
	$(FC) $(OPT) -c visweak.f90

EDA.o : EDA.f90 $(modules)
	$(FC) $(OPT) -c EDA.f90

CDFT.o : CDFT.f90 $(modules)
	$(FC) $(OPT) -c CDFT.f90

ETS_NOCV.o : ETS_NOCV.f90 $(modules)
	$(FC) $(OPT) -c ETS_NOCV.f90

NAONBO.o : NAONBO.f90 $(modules)
	$(FC) $(OPT) -c NAONBO.f90

grid.o : grid.f90 $(modules)
	$(FC) $(OPT) -c grid.f90

PBC.o : PBC.f90 $(modules)
	$(FC) $(OPT) -c PBC.f90

hyper_polar.o : hyper_polar.f90 $(modules)
	$(FC) $(OPT) -c hyper_polar.f90
	
deloc_aromat.o : deloc_aromat.f90 $(modules)
	$(FC) $(OPT) -c deloc_aromat.f90


noGUI/dislin_d_empty.o : noGUI/dislin_d_empty.f90
	$(FC) $(OPT) -c noGUI/dislin_d_empty.f90 -o noGUI/dislin_d_empty.o -diag-disable 6178,6843


# Interfaces of libreta-ESP to Multiwfn

libreta.o: ${LIBRETAPATH}/libreta.f90 hrr_012345.o blockhrr_012345.o ean.o eanvrr_012345.o boysfunc.o
	$(FC) $(OPT) -c ${LIBRETAPATH}/libreta.f90

# Pure libreta files for ESP

hrr_012345.o: ${LIBRETAPATH}/hrr_012345.f90
	$(FC) $(OPT) -diag-disable 6843 $(SIMD) -c ${LIBRETAPATH}/hrr_012345.f90

blockhrr_012345.o: ${LIBRETAPATH}/blockhrr_012345.f90
	$(FC) -O1 -diag-disable 6843 $(SIMD) -c ${LIBRETAPATH}/blockhrr_012345.f90

ean.o: ${LIBRETAPATH}/ean.f90 hrr_012345.o eanvrr_012345.o boysfunc.o ${LIBRETAPATH}/ean_data1.h ${LIBRETAPATH}/ean_data2.h
	$(FC) $(OPT) -c ${LIBRETAPATH}/ean.f90

eanvrr_012345.o: ${LIBRETAPATH}/eanvrr_012345.f90 boysfunc.o
	$(FC) $(OPT) -c ${LIBRETAPATH}/eanvrr_012345.f90

boysfunc.o: ${LIBRETAPATH}/boysfunc.f90 ${LIBRETAPATH}/boysfunc_data1.h ${LIBRETAPATH}/boysfunc_data2.h
	$(FC) $(OPT) -c ${LIBRETAPATH}/boysfunc.f90

# libreta-ERI

naiveeri.o: ${LIBRETAPATH}/naiveeri.f90 ryspoly.o
	$(FC) $(OPT) -c ${LIBRETAPATH}/naiveeri.f90
	
ryspoly.o: ${LIBRETAPATH}/ryspoly.f90
	$(FC) $(OPT) -c ${LIBRETAPATH}/ryspoly.f90
```

**Comment by kjelljorner** [comment]
Glad that it worked out using the modified Makefile. It's a bit difficult to troubleshoot this without an actual functional libdislin on my system, but you could try this and see if it works. It would search for libdislin in the source folder, but you can also try to make a copy into `/usr/local/lib`.

```cmake
cmake_minimum_required(VERSION 3.18)
project(my_proj LANGUAGES C Fortran) # C is needed to discover Homebrew OpenBLAS

# Options
option(WITH_OpenMP "Build with OpenMP")
option(WITH_GUI "Build with GUI")

# Find BLAS and LAPACK
include(CMakeFindDependencyMacro)
find_dependency(BLAS)
find_dependency(LAPACK)
find_package(BLAS)
find_package(LAPACK)

# Find OpenMP
if(WITH_OpenMP)
  find_package(OpenMP REQUIRED)
endif()

# Find X11. Can be added for GUI, if DISLIN is also available
if(WITH_GUI)
  find_package(X11 REQUIRED)
  find_library(dislin
    NAMES dislin dislin_d dislin_d.11.1.0
    PATHS ${PROJECT_SOURCE_DIR}
    REQUIRED
  )
endif()

# Turn on preprocessor
set(CMAKE_Fortran_PREPROCESS ON)

# Add source files
file(GLOB srcs CONFIGURE_DEPENDS
  ${PROJECT_SOURCE_DIR}/*.f90
  ${PROJECT_SOURCE_DIR}/*.F
  ${PROJECT_SOURCE_DIR}/libreta_hybrid/*.f90
)
if(NOT WITH_GUI)
  list(APPEND srcs ${PROJECT_SOURCE_DIR}/noGUI/dislin_d_empty.f90)
endif()

# Add executable
add_executable(multiwfn ${srcs})
target_link_libraries(
  multiwfn
  PRIVATE
  ${BLAS_LIBRARIES}
  ${LAPACK_LIBRARIES}
  $<$<BOOL:${OpenMP_Fortran_FOUND}>:OpenMP::OpenMP_Fortran>
  $<$<BOOL:${WITH_GUI}>:${X11_LIBRARIES}>
  $<$<BOOL:${WITH_GUI}>:dislin>
)
target_compile_options(multiwfn PRIVATE -ffree-line-length-none)

# Install
install(TARGETS multiwfn)
install(FILES settings.ini DESTINATION ${CMAKE_INSTALL_PREFIX}/etc/multiwfn)
```

**Comment by kjelljorner** [comment]
I posted a question [here](https://groups.google.com/g/DISLIN-users/c/t0YRbIp-_sg) on the DISLIN discussion group whether they will release a native version of DISLIN for Apple Silicon

**Comment by kjelljorner** [comment]
An [update](https://groups.google.com/g/DISLIN-users/c/t0YRbIp-_sg) from the author that it will be available in a few months. I will revisit at that point

**Comment by lxsjgzs** [comment]
It’s really an exciting news for MacOS users that dislin can be build on Apple Silicon Mac by Rosetta and the native build will released in few months. 

I just copied the CMakelists.txt in this issue. When I try `cmake -B build -DWITH_GUI=ON -DWITH_OpenMP=ON`, it seems okay but the time when I `make`, it hint me ld: ***not found -ldislin, it seems the `LIBRARY_PATH` should be configured and located to the dislin folder. Finally I successfully got the Multiwfn file. But the terminal  print that LD library not found for ‘__XtStrings’  the time when I try to execute it. I’m trying to work out this issue these days but found less information about it. It seems need a library named like *xt. I will try to find it out tomorrow. 
Have a nice week Mr. Jorner!

**Comment by kjelljorner** [comment]
With the current CMakeLists.txt, the libdislin_d.11.1.0 should either be placed in the root folder of the repository, `${PROJECT_SOURCE_DIR}`, or in a path that is read by the `ld` linker. It seems that the default search directories are
```
/usr/local/lib
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
```
I think you add to this list when setting the `LIBRARY_PATH` variable.

Not sure about the other error. Have you installed [libx11](https://formulae.brew.sh/formula/libx11) with homebrew?

**Comment by lxsjgzs** [comment]
Another good news Mr. Jorner! I just searched and installed another two libraries to PATH then builded it with GUI, the multiwfn executed normally with GUI such as Pic.1 and seems as well as previous. Let me review the details and dependencies then PR it tomorrow.

<img width="1115" alt="截屏2022-06-26 上午3 36 36" src="https://user-images.githubusercontent.com/42400748/175788654-7b97730a-d218-4e50-8480-de9be7f3aece.png">

Pic.1

**Comment by kjelljorner** [comment]
Great news @lxsjgzs! Looking forward to the PR. We want it to be as general as possible for the user. One option is to be able to pass a directory where dislin is installed as a variable to cmake

**Comment by lxsjgzs** [comment]
Although the multiwfn GUI verison had been successfully built use the lack of libraries as `libXt` and `libopenmotif`, but it can just call the X11 selection GUI, frame such as view MOs, spectra etc. cannot display correctly. I wonder if the different versions library should be built in instead of the newest version. But at least it can be a way to built for Mac.

**Comment by kjelljorner** [comment]
@lxsjgzs I was inspired by your attempt, and tried to troubleshoot this via Rosetta. I got something in the end that seems to work, including viewing orbitals (you might have to click the buttons to rotate the molecule to see it). There's a few steps. Please let me know if it works, and I will create the pull request myself.

## Install DISLIN

1. Download the right distribution from https://www.dislin.de/darwin.html
2. Unpack the .tar.gz file and go into the folder
3. Set the preferred install directory for DISLIN with for example `export DISLIN=$HOME/bin/dislin`
4. Run the installation script with `./INSTALL`
5. Patch the library install_name with `install_name_tool -id $DISLIN/libdislin_d.dylib $DISLIN/libdislin_d.dylib`

## Install dependencies

`brew install openmotif`

## Build multiwfn

Use the following `CMakeLists.txt` and install with `cmake -B build -DWITH_GUI=ON -DDISLIN_DIR=$DISLIN` where `$DISLIN` is the folder where you installed DISLIN.

```cmake
cmake_minimum_required(VERSION 3.18)
project(my_proj LANGUAGES C Fortran) # C is needed to discover Homebrew OpenBLAS

# Options
option(WITH_OpenMP "Build with OpenMP")
option(WITH_GUI "Build with GUI")

# Find BLAS and LAPACK
include(CMakeFindDependencyMacro)
find_dependency(BLAS)
find_dependency(LAPACK)
find_package(BLAS)
find_package(LAPACK)

# Find OpenMP
if(WITH_OpenMP)
  find_package(OpenMP REQUIRED)
endif()

# Find graphics libraries
if(WITH_GUI)
  find_library(
    dislin
    NAMES dislin_d
    PATHS ${DISLIN_DIR}
    REQUIRED
  )
  find_library(
    Xm
    NAMES Xm
    REQUIRED
  )
endif()

# Turn on preprocessor
set(CMAKE_Fortran_PREPROCESS ON)

# Add source files
file(GLOB srcs CONFIGURE_DEPENDS
  ${PROJECT_SOURCE_DIR}/*.f90
  ${PROJECT_SOURCE_DIR}/*.F
  ${PROJECT_SOURCE_DIR}/libreta_hybrid/*.f90
)
if(NOT WITH_GUI)
  list(APPEND srcs ${PROJECT_SOURCE_DIR}/noGUI/dislin_d_empty.f90)
endif()

# Add executable
add_executable(multiwfn ${srcs})
target_link_libraries(
  multiwfn
  PRIVATE
  ${BLAS_LIBRARIES}
  ${LAPACK_LIBRARIES}
  $<$<BOOL:${OpenMP_Fortran_FOUND}>:OpenMP::OpenMP_Fortran>
  $<$<BOOL:${WITH_GUI}>:${dislin}>
  $<$<BOOL:${WITH_GUI}>:${Xm}>
)
target_compile_options(multiwfn PRIVATE -ffree-line-length-none)

# Install
install(TARGETS multiwfn)
install(FILES settings.ini DESTINATION ${CMAKE_INSTALL_PREFIX}/etc/multiwfn)

```

**Comment by lxsjgzs** [comment]
The command is also working on my Intel version Mac. By packeting the DISLIN use command `install_name_tool -id $DISLIN/libdislin_d.dylib $DISLIN/libdislin_d.dylib` and using the latest `CMakeLists.txt` here. The `-DWITH_OpenMP=ON` also works. Thank you Mr. Jorner.  That's a really a hard work.

**Comment by kjelljorner** [comment]
@lxsjgzs Many thanks for your help. I just merged the pull request.
